#!/usr/bin/env bash

# git stashしたリストの中から選択し、applyするスクリプト
selected_stash=$(git stash list | fzf --height=15 --prompt="Select a stash to apply: ")

if [[ -z "$selected_stash" ]]; then
    echo "No stash selected. Aborting."
    exit 1
fi

stash_name=$(echo "$selected_stash" | sed -E 's/^(stash@\{[0-9]+\}):.*/\1/')
git stash apply "$stash_name"